version: 2
updates:
  # Go modules
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5

  # Docker
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday

  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
